name: .NET Build & Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore RealEstateApp/RealEstateApp.sln

    - name: Build solution
      run: dotnet build RealEstateApp/RealEstateApp.sln --no-restore --configuration Debug

    #- name: Run tests
    #  run: dotnet test --no-restore --verbosity normal


    - name: Publish
      run: dotnet publish RealEstateApp/Server/RealEstateApp.Server.csproj -c Release -o published